<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>article</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
</head>
<body>
<h1 id="microtasks">Microtasks</h1>
<p>Promise handlers <code>.then</code>/<code>.catch</code>/<code>.finally</code> are always asynchronous.</p>
<p>Even when a Promise is immediately resolved, the code on the lines <em>below</em> <code>.then</code>/<code>.catch</code>/<code>.finally</code> will still execute before these handlers.</p>
<p>Here’s a demo:</p>
<p>```js run let promise = Promise.resolve();</p>
<p>promise.then(() =&gt; alert(“promise done!”));</p>
<p>alert(“code finished”); // this alert shows first ```</p>
<p>If you run it, you see <code>code finished</code> first, and then <code>promise done!</code>.</p>
<p>That’s strange, because the promise is definitely done from the beginning.</p>
<p>Why did the <code>.then</code> trigger afterwards? What’s going on?</p>
<h2 id="microtasks-queue">Microtasks queue</h2>
<p>Asynchronous tasks need proper management. For that, the ECMA standard specifies an internal queue <code>PromiseJobs</code>, more often referred to as the “microtask queue” (V8 term).</p>
<p>As stated in the <a href="https://tc39.github.io/ecma262/#sec-jobs-and-job-queues">specification</a>:</p>
<ul>
<li>The queue is first-in-first-out: tasks enqueued first are run first.</li>
<li>Execution of a task is initiated only when nothing else is running.</li>
</ul>
<p>Or, to put it more simply, when a promise is ready, its <code>.then/catch/finally</code> handlers are put into the queue; they are not executed yet. When the JavaScript engine becomes free from the current code, it takes a task from the queue and executes it.</p>
<p>That’s why “code finished” in the example above shows first.</p>
<p><img src="promiseQueue.svg" /></p>
<p>Promise handlers always go through this internal queue.</p>
<p>If there’s a chain with multiple <code>.then/catch/finally</code>, then every one of them is executed asynchronously. That is, it first gets queued, then executed when the current code is complete and previously queued handlers are finished.</p>
<p><strong>What if the order matters for us? How can we make <code>code finished</code> appear after <code>promise done</code>?</strong></p>
<p>Easy, just put it into the queue with <code>.then</code>:</p>
<p><code>js run Promise.resolve()   .then(() =&gt; alert("promise done!"))   .then(() =&gt; alert("code finished"));</code></p>
<p>Now the order is as intended.</p>
<h2 id="unhandled-rejection">Unhandled rejection</h2>
<p>Remember the <code>unhandledrejection</code> event from the article <a href="info:promise-error-handling" class="uri">info:promise-error-handling</a>?</p>
<p>Now we can see exactly how JavaScript finds out that there was an unhandled rejection.</p>
<p><strong>An “unhandled rejection” occurs when a promise error is not handled at the end of the microtask queue.</strong></p>
<p>Normally, if we expect an error, we add <code>.catch</code> to the promise chain to handle it:</p>
<p>```js run let promise = Promise.reject(new Error(“Promise Failed!”)); <em>!</em> promise.catch(err =&gt; alert(‘caught’)); <em>/!</em></p>
<p>// doesn’t run: error handled window.addEventListener(‘unhandledrejection’, event =&gt; alert(event.reason)); ```</p>
<p>But if we forget to add <code>.catch</code>, then, after the microtask queue is empty, the engine triggers the event:</p>
<p>```js run let promise = Promise.reject(new Error(“Promise Failed!”));</p>
<p>// Promise Failed! window.addEventListener(‘unhandledrejection’, event =&gt; alert(event.reason)); ```</p>
<p>What if we handle the error later? Like this:</p>
<p>```js run let promise = Promise.reject(new Error(“Promise Failed!”)); <em>!</em> setTimeout(() =&gt; promise.catch(err =&gt; alert(‘caught’)), 1000); <em>/!</em></p>
<p>// Error: Promise Failed! window.addEventListener(‘unhandledrejection’, event =&gt; alert(event.reason)); ```</p>
<p>Now, if we run it, we’ll see <code>Promise Failed!</code> first and then <code>caught</code>.</p>
<p>If we didn’t know about the microtasks queue, we could wonder: “Why did <code>unhandledrejection</code> handler run? We did catch and handle the error!”</p>
<p>But now we understand that <code>unhandledrejection</code> is generated when the microtask queue is complete: the engine examines promises and, if any of them is in the “rejected” state, then the event triggers.</p>
<p>In the example above, <code>.catch</code> added by <code>setTimeout</code> also triggers. But it does so later, after <code>unhandledrejection</code> has already occurred, so it doesn’t change anything.</p>
<h2 id="summary">Summary</h2>
<p>Promise handling is always asynchronous, as all promise actions pass through the internal “promise jobs” queue, also called “microtask queue” (V8 term).</p>
<p>So <code>.then/catch/finally</code> handlers are always called after the current code is finished.</p>
<p>If we need to guarantee that a piece of code is executed after <code>.then/catch/finally</code>, we can add it into a chained <code>.then</code> call.</p>
<p>In most Javascript engines, including browsers and Node.js, the concept of microtasks is closely tied with the “event loop” and “macrotasks”. As these have no direct relation to promises, they are covered in another part of the tutorial, in the article <a href="info:event-loop" class="uri">info:event-loop</a>.</p>
</body>
</html>
